/** Fails fast at boot rather than at the first login attempt. */
function required(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required environment variable: ${name}`);
  return value;
}

export const config = {
  port: Number(process.env.PORT ?? 8787),
  isProd: process.env.NODE_ENV === 'production',

  /** Where the SPA is served from — used for redirects and CORS. */
  appUrl: process.env.APP_URL ?? 'http://localhost:5173',

  jo1n: {
    issuer: required('JO1N_ISSUER'),
    clientId: required('JO1N_CLIENT_ID'),
    clientSecret: required('JO1N_CLIENT_SECRET'),
    redirectUri: required('JO1N_REDIRECT_URI'),
    /** Must match the client's default_audience in JO1N ID. */
    audience: process.env.JO1N_AUDIENCE ?? 'artbank-api',

    // Endpoints come from JO1N ID's /.well-known/openid-configuration, which
    // is now generated by its tested discovery service. These stay as escape
    // hatches for local instances or if discovery is unreachable at boot.
    authorizeUrl: process.env.JO1N_AUTHORIZE_URL,
    tokenUrl: process.env.JO1N_TOKEN_URL,
    jwksUrl: process.env.JO1N_JWKS_URL,
    userinfoUrl: process.env.JO1N_USERINFO_URL,
    // Not part of OIDC discovery — JO1N's own password-registration API.
    registerUrl: process.env.JO1N_REGISTER_URL,
  },

  supabase: {
    url: required('SUPABASE_URL'),
    // Service role: bypasses RLS. Authorization is enforced in this API.
    // Must never be exposed to the browser or prefixed VITE_.
    serviceRoleKey: required('SUPABASE_SERVICE_ROLE_KEY'),
  },

  session: {
    cookieName: 'artbank_session',
    /** Non-sensitive, JS-readable "is there probably a session" hint. */
    hintCookieName: 'artbank_sess',
    ttlDays: 7,
  },
} as const;

export type Jo1nEndpoints = {
  authorize: string;
  token: string;
  jwks: string;
  userinfo: string;
  register: string;
};
