-- Competition finalist artworks: unpriced drafts, not publicly visible until
-- an admin sets a price and flips status to 'published'.
insert into public.artworks (id, title, artist, currency, likes, verified, gradient, image_url, status) values
  ('finalist-aadya-mishra', 'Untitled', 'Aadya Mishra', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/aadya-mishra-1.jpg', 'draft'),
  ('finalist-cyrus-keh-pak-jinn', 'Untitled', 'Cyrus Keh Pak-jinn', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/cyrus-keh-pak-jinn-1.jpg', 'draft'),
  ('finalist-elisha-cailey-binti-muhammad-faiz-asna', 'Untitled', 'Elisha Cailey binti Muhammad Faiz Asna', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/elisha-cailey-binti-muhammad-faiz-asna-1.jpg', 'draft'),
  ('finalist-lee-yun-xi', 'Untitled', 'Lee Yun Xi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/lee-yun-xi-1.jpg', 'draft'),
  ('finalist-muhammad-nael-iskandar', 'Untitled', 'Muhammad Nael Iskandar', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/muhammad-nael-iskandar-1.jpg', 'draft'),
  ('finalist-nawra-aisyaa', 'Untitled', 'Nawra Aisyaa', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/nawra-aisyaa-1.jpg', 'draft'),
  ('finalist-ng-kai-zee', 'Untitled', 'Ng Kai Zee', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/ng-kai-zee-1.jpg', 'draft'),
  ('finalist-noelle-ng-tze-yu', 'Untitled', 'Noelle Ng Tze Yu', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/noelle-ng-tze-yu-1.jpg', 'draft'),
  ('finalist-tuah-isaac', 'Untitled', 'Tuah Isaac', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/tuah-isaac-1.jpg', 'draft'),
  ('finalist-venbha-pregas', 'Untitled', 'Venbha Pregas', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/venbha-pregas-1.jpg', 'draft'),
  ('finalist-aeris-lim-kai-xia', 'Untitled', 'Aeris Lim Kai Xia', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/aeris-lim-kai-xia-1.jpg', 'draft'),
  ('finalist-benjamin-liew-jun-yong', 'Untitled', 'Benjamin Liew Jun Yong', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/benjamin-liew-jun-yong-1.jpg', 'draft'),
  ('finalist-heng-yi-lin', 'Untitled', 'Heng Yi Lin', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/heng-yi-lin-1.jpg', 'draft'),
  ('finalist-ismail-irfan-bin-ruzaidin', 'Untitled', 'Ismail Irfan bin Ruzaidin', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/ismail-irfan-bin-ruzaidin-1.jpg', 'draft'),
  ('finalist-phuah-jing-xuan', 'Untitled', 'Phuah Jing Xuan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/phuah-jing-xuan-1.jpg', 'draft'),
  ('finalist-pua-yan-xi', 'Untitled', 'Pua Yan Xi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/pua-yan-xi-1.jpg', 'draft'),
  ('finalist-tan-xuan-ee', 'Untitled', 'Tan Xuan Ee', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/tan-xuan-ee-1.jpg', 'draft'),
  ('finalist-tang-ee-than', 'Untitled', 'Tang Ee Than', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/tang-ee-than-1.jpg', 'draft'),
  ('finalist-yee-jing-xuan', 'Untitled', 'Yee Jing Xuan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/yee-jing-xuan-1.jpg', 'draft'),
  ('finalist-aabarana-a-p-gunasegaran', 'Untitled', 'Aabarana A/P Gunasegaran', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/aabarana-a-p-gunasegaran-1.jpg', 'draft'),
  ('finalist-amraeisz-a-l-ravindran', 'Untitled', 'Amraeisz A/L Ravindran', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/amraeisz-a-l-ravindran-1.jpg', 'draft'),
  ('finalist-bernice-tan', 'Untitled', 'Bernice Tan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/bernice-tan-1.jpg', 'draft'),
  ('finalist-charice-leong', 'Untitled', 'Charice Leong', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/charice-leong-1.jpg', 'draft'),
  ('finalist-elise-kong', 'Untitled', 'Elise Kong', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/elise-kong-1.jpg', 'draft'),
  ('finalist-gabrielle-ng', 'Untitled', 'Gabrielle Ng', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/gabrielle-ng-1.jpg', 'draft'),
  ('finalist-isaac-lee-cheng-you', 'Untitled', 'Isaac Lee Cheng You', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/isaac-lee-cheng-you-1.jpg', 'draft'),
  ('finalist-kaarunesh-nair-a-l-sreekumaran', 'Untitled', 'Kaarunesh Nair A/L Sreekumaran', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/kaarunesh-nair-a-l-sreekumaran-1.jpg', 'draft'),
  ('finalist-lim-yuan-qing', 'Untitled', 'Lim Yuan Qing', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/lim-yuan-qing-1.jpg', 'draft'),
  ('finalist-low-reica', 'Untitled', 'Low Reica', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/low-reica-1.jpg', 'draft'),
  ('finalist-rachel-tan-rui-yi', 'Untitled', 'Rachel Tan Rui Yi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/rachel-tan-rui-yi-1.jpg', 'draft'),
  ('finalist-sheryn-yee', 'Untitled', 'Sheryn Yee', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/sheryn-yee-1.jpg', 'draft'),
  ('finalist-wan-nur-syaza-deana', 'Untitled', 'Wan Nur Syaza Deana', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/wan-nur-syaza-deana-1.jpg', 'draft'),
  ('finalist-chey-yu-jie', 'Untitled', 'Chey Yu Jie', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/chey-yu-jie-1.jpg', 'draft'),
  ('finalist-chin-yi-yan', 'Untitled', 'Chin Yi Yan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/chin-yi-yan-1.jpg', 'draft'),
  ('finalist-isabelle-lee-ruo-ning', 'Untitled', 'Isabelle Lee Ruo Ning', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/isabelle-lee-ruo-ning-1.jpg', 'draft'),
  ('finalist-melissa-wong-jing-mun', 'Untitled', 'Melissa Wong Jing Mun', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/melissa-wong-jing-mun-1.jpg', 'draft'),
  ('finalist-olivia-on-li-yaa', 'Untitled', 'Olivia On Li Yaa', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/olivia-on-li-yaa-1.jpg', 'draft'),
  ('finalist-shick-en-qi', 'Untitled', 'Shick En Qi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/shick-en-qi-1.jpg', 'draft'),
  ('finalist-thejal-huma', 'Untitled', 'Thejal Huma', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/thejal-huma-1.jpg', 'draft'),
  ('finalist-tiffany-low-mei-xuan', 'Untitled', 'Tiffany Low Mei Xuan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/tiffany-low-mei-xuan-1.jpg', 'draft'),
  ('finalist-winnie-chan-xin-ning', 'Untitled', 'Winnie Chan Xin Ning', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/winnie-chan-xin-ning-1.jpg', 'draft'),
  ('finalist-yap-en-qi', 'Untitled', 'Yap En Qi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/yap-en-qi-1.jpg', 'draft'),
  ('finalist-chua-wei-qian', 'Untitled', 'Chua Wei Qian', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/chua-wei-qian-1.jpg', 'draft'),
  ('finalist-edris-tan-wei-xuan', 'Untitled', 'Edris Tan Wei Xuan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/edris-tan-wei-xuan-1.jpg', 'draft'),
  ('finalist-khoo-thien-yi', 'Untitled', 'Khoo Thien Yi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/khoo-thien-yi-1.jpg', 'draft'),
  ('finalist-mahalaxhanya-a-p-bala-subramaniam', 'Untitled', 'Mahalaxhanya A/P Bala Subramaniam', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/mahalaxhanya-a-p-bala-subramaniam-1.jpg', 'draft'),
  ('finalist-nimitha-sri-a-p-ganesan', 'Untitled', 'Nimitha Sri A/P Ganesan', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/nimitha-sri-a-p-ganesan-1.jpg', 'draft'),
  ('finalist-nur-fatihah-nafisa-binti-muhammad-faisal', 'Untitled', 'Nur Fatihah Nafisa binti Muhammad Faisal', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/nur-fatihah-nafisa-binti-muhammad-faisal-1.jpg', 'draft'),
  ('finalist-nurfaizah-najihah-binti-mohd-khairil-faizi', 'Untitled', 'Nurfaizah Najihah binti Mohd Khairil Faizi', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/nurfaizah-najihah-binti-mohd-khairil-faizi-1.jpg', 'draft'),
  ('finalist-wan-nur-syaza-sofea', 'Untitled', 'Wan Nur Syaza Sofea', 'RM', 0, false, '', 'https://uccqvrotcisbwvcceisv.supabase.co/storage/v1/object/public/artwork-images/finalists/wan-nur-syaza-sofea-1.jpg', 'draft')
on conflict (id) do nothing;

